version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/packages/hs-react-ui
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
            - run: npm run build-storybook
workflows:
    build-and-test:
      jobs:
        - build-and-test